logging:
  level:
    org:
      flywaydb: INFO
    io:
      ebean:
        SQL: DEBUG
        TXN: DEBUG

datasource:
  db:
    username: fosdem
    password: "Fosdem.2021"
    databaseUrl: jdbc:postgresql://localhost:5432/fosdem21
